name: Terraform ECR

on:
  workflow_dispatch:

jobs:
  terraform-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
      - name: Terraform Apply (ECR only)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -target=aws_ecr_repository.globant_api -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}"
      - name: Commit and push Terraform lock file
        continue-on-error: true
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add terraform/.terraform.lock.hcl
          git commit -m "Update Terraform lock file" || echo "No changes to commit"
          git push
